// <auto-generated />
namespace LICENTA4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddImagesIntoPosts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddImagesIntoPosts));
        
        string IMigrationMetadata.Id
        {
            get { return "202105172055070_AddImagesIntoPosts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
